export { default as ForgotPassword } from './auth/ForgotPassword/ForgotPassword'
export { default as Login } from './auth/Login/Login'
export { default as Register } from './auth/Register/Register'
export { default as ResetSuccessful } from './auth/ResetSuccessful/ResetSuccessful'
export { default as UnAuthorized } from './auth/UnAuthorized/UnAuthorized'
